#!/bin/bash
set -e
set -o pipefail
sudo pacman -U \
  https://archive.archlinux.org/packages/b/boost/boost-1.68.0-2-x86_64.pkg.tar.xz \
  https://archive.archlinux.org/packages/b/boost-libs/boost-libs-1.68.0-2-x86_64.pkg.tar.xz
yay -S rethinkdb
