export const Admin = true;
export const AdminOnly = true;
export const OptionalAuth = true;
export const InvalidToken: 'InvalidToken' = 'InvalidToken';
export const InvalidAppId: 'InvalidAppId' = 'InvalidAppId';
export const QuotaExcess: 'QuotaExcess' = 'QuotaExcess';
export const NoPermission: 'NoPermission' = 'NoPermission';
export const UserNotFound: 'UserNotFound' = 'UserNotFound';
export const Duplicated: 'Duplicated' = 'Duplicated';
